FA.JustBlog/Areas/Admin/Models/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FA.JustBlog.Areas.Admin.Models
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string UrlSlug { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
    }
}

FA.JustBlog/Areas/Admin/Controllers/CategoryController.cs
using FA.JustBlog.Areas.Admin.Models;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using FA.JustBlog.Core.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepo _categoryRepository;
        public CategoryController(ICategoryRepo categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            var categories = _categoryRepository.GetAllCategories();
            return View(categories);
        }
        
        public IActionResult Details(int id)
        {
            var category = _categoryRepository.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpGet]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Create(CategoryViewModel categoryView)
        {
            if (ModelState.IsValid)
            {
                var category = MapToCategory(categoryView);
                _categoryRepository.AddCategory(category);
                return RedirectToAction("Index");
            }
            return View();
        }

        
        [HttpGet]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Edit(int id)
        {
            var category = _categoryRepository.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            var categoryModel = MapToViewModel(category);
            return View(categoryModel);
        }
        [HttpPost]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Edit(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = MapToCategory(categoryViewModel);
                _categoryRepository.UpdateCategory(category);
                return RedirectToAction("Index");
            }
            return View();
        }

        private Category MapToCategory(CategoryViewModel model)
        {
            Category category = new()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                UrlSlug = model.UrlSlug,
            };
            return category;
        }

        private CategoryViewModel MapToViewModel(Category category) {
            CategoryViewModel model = new()
            {
                Id = category.Id,
                Name = category.Name,
                Description = category.Description,
                UrlSlug = category.UrlSlug
            };
            return model;
        }
    }
}

FA.JustBlog/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Areas.Admin.Models;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using FA.JustBlog.Core.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly IPostRepo postRepo;
        private readonly ICategoryRepo categoryRepo;
        public PostController(IPostRepo postrepo, ICategoryRepo cate)
        {
            postRepo = postrepo;
            categoryRepo = cate;
        }
        public IActionResult Index()
        {
            IList<Post> list = postRepo.GetAllPosts();
            return View(list);
        }

        public IActionResult LatestPosts(int size = 15)
        {
            IList<Post> list = postRepo.GetLatestPost(size);
            return View(list);
        }

        public IActionResult MostViewedPosts(int size = 15)
        {
            IList<Post> list = postRepo.GetMostViewedPost(size);
            return View(list);
        }

        public IActionResult MostInterestingPosts()
        {
            var posts = postRepo.GetAllPosts().OrderByDescending(p => p.TotalRate).ToList();
            return View(posts);
        }

        public IActionResult PublishedPosts()
        {
            IList<Post> list = postRepo.GetPublisedPosts();
            return View(list);
        }

        [Authorize(Roles = Roles.BlogOwner)]
        public IActionResult UnPublishedPosts()
        {
            IList<Post> list = postRepo.GetUnpublisedPosts();
            return View(list);
        }

        [HttpGet]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Create()
        {
            var categories = categoryRepo.GetAllCategories();
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Create(PostDto model)
        {
            var categories = categoryRepo.GetAllCategories();
            ViewBag.Categories = categories;
            if (ModelState.IsValid)
            {
                Post postToCreate = mapToPost(model);
                postToCreate.Modified = model.PostedOn;
                postRepo.AddPost(postToCreate);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Details(int id)
        {
            Post post = postRepo.FindPostById(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        [HttpGet]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Edit(int id)
        {
            var categories = categoryRepo.GetAllCategories();
            ViewBag.Categories = categories;
            Post post = postRepo.FindPostById(id);
            if (post == null)
            {
                return NotFound();
            }
            PostDto dto = mapperToDto(post);
            return View(dto);
        }

        [HttpPost]
        [Authorize(Roles = $"{Roles.BlogOwner}, {Roles.Contributor}")]
        public IActionResult Edit(int id, PostDto dto)
        {
            if (ModelState.IsValid)
            {
                var post = mapToPost(dto);
                post.Modified = DateTime.Now;
                postRepo.UpdatePost(post);
                return RedirectToAction("Index");
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpGet]
        [Authorize(Roles = Roles.BlogOwner)]
        public IActionResult Delete(int id)
        {
            var post = postRepo.FindPostById(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        [HttpPost]
        [Authorize(Roles = $"{Roles.BlogOwner}")]
        public IActionResult ConfirmDelete(int id)
        {
            Post postToDelete = postRepo.FindPostById(id);
            if (postToDelete == null)
            {
                return NoContent();
            }
            postRepo.DeletePost(postToDelete);
            return RedirectToAction("Index");
        }

        private Post mapToPost(PostDto model)
        {
            Post post = new()
            {
                Id = model.Id,
                Title = model.Title,
                UrlSlug = model.UrlSlug,
                ShortDescription = model.ShortDescription,
                PostContent = model.PostContent,
                Published = model.Published,
                PostedOn = model.PostedOn,
                Modified = model.Modified,
                CategoryId = model.CategoryId
            };
            return post;
        }

        private PostDto mapperToDto(Post post)
        {
            PostDto dto = new()
            {
                Id = post.Id,
                Title = post.Title,
                UrlSlug = post.UrlSlug,
                ShortDescription = post.ShortDescription,
                PostContent = post.PostContent,
                Published = post.Published,
                PostedOn = post.PostedOn,
                Modified = post.Modified,
                CategoryId = post.CategoryId
            };
            return dto;
        }

    }
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostRepo postRepo;
        public PostController(IPostRepo repo)
        {
            postRepo = repo;
        }

        //display all posts
        public IActionResult Index()
        {
            IList<Post> posts = postRepo.GetAllPosts();
            return View(posts);
        }

        //display single post by id
        public IActionResult PostDetails(int id)
        {
            Post post = postRepo.FindPostById(id);
            if (post == null)
            {
                return NoContent();
            }
            return View("Views/Post/Details.cshtml", post);
        }

        //display latest posts
        public IActionResult LastestPosts(int size = 5)
        {
            IList<Post> posts = postRepo.GetLatestPost(size);
            return View("Views/Post/Index.cshtml", posts);
        }

        //[System.Web.Mvc.ChildActionOnly]
        public IActionResult AboutCard()
        {
            return PartialView("_PartialAboutCard");
        }

        public Post GetPostById(int id)
        {
            return postRepo.FindPostById(id);
        }

        [Route("post/{year}/{month}/{urlslug}")]
        public ActionResult Details(int year, int month, string urlslug)
        {
            var post = postRepo.FindPost(year, month, urlslug);
            if (post == null)
                return NotFound();
            return View(post);
        }

        // get post by category name
        [Route("post/category/{category}")]
        public IActionResult Category(string category)
        {
            try
            {
                IList<Post> postsByCate = postRepo.GetPostsByCategory(category);
                return View("Views/Post/Index.cshtml", postsByCate);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(ReturnErrorView));
            }
        }

        // get posts by tag name
        [Route("post/tag/{tagUrlSlug}")]
        public IActionResult Tag(string tagUrlSlug)
        {
            try
            {
                IList<Post> postsByTag = postRepo.GetPostsByTag(tagUrlSlug);
                return View("Views/Post/Index.cshtml", postsByTag);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(ReturnErrorView));
            }
        }

        [HttpPost]
        //[Route("post/search")]
        public IActionResult Search(string query)
        {
            IList<Post> posts = postRepo.FindPostByTitleOrDescription(query);
            return View("Views/Post/Index.cshtml", posts);
        }
        public ViewResult ReturnErrorView()
        {
            return View("Views/Shared/Error.cshtml");
        }
    }
}

FA.JustBlog/ViewComponents/LatestPostsViewComponent.cs
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.ViewComponents
{
    public class LatestPostsViewComponent : ViewComponent
    {
        IPostRepo repo;

        public LatestPostsViewComponent(IPostRepo repo)
        {
            this.repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            int postCount = 5;
            var lastests = repo.GetLatestPost(postCount);
            return View(lastests);
        }
    }
}

FA.JustBlog/ViewComponents/MostViewedViewComponent.cs
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.ViewComponents
{
    public class MostViewedViewComponent : ViewComponent
    {
        IPostRepo repo;

        public MostViewedViewComponent(IPostRepo repo)
        {
            this.repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            int postCount = 5;
            var mostViewed = repo.GetMostViewedPost(postCount);
            return View(mostViewed);
        }
    }
}

FA.JustBlog/Views/Post/Details.cshtml
@model FA.JustBlog.Core.Models.Post
@* @{
    ViewData["Title"] = Model.Title;
} *@
<!-- Page Header-->
<header class="masthead" style="background-image: url('/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>@Model.Title</h1>
                    <h2 class="subheading">@Html.Raw(@Model.ShortDescription)</h2>
                    <span class="meta">
                        Posted on @Model.PostedOn
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>
                    @Html.Raw(@Model.PostContent)
                </p>
            </div>
        </div>
    </div>
</article>

FA.JustBlog/Views/Post/Index.cshtml
@using FA.JustBlog.ExtensionHelpers
@model IList<FA.JustBlog.Core.Models.Post>
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .post-tag{
        background-color: black;
        padding: 5px 15px;
        color: white;
        margin-right: 10px
    }

    .post-tag a{
        color: white;
    }
</style>

<!-- Page Header-->
<header class="masthead" style="background-image: url('/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var post in Model)
            {
                <div class="post-preview">
                    <h2 class="post-title">
                        @Html.ActionLink(post.Title, "Details", "Post", new { year = post.PostedOn.Year, month = post.PostedOn.Month, urlslug = post.UrlSlug }, null)
                    </h2>
                    <h3 class="post-subtitle">@Html.Raw(@post.ShortDescription)</h3>
                    @Html.PostedTime(post)
                    <p class="post-meta"> Category: @Html.CategoryLink(post.Category.Name, post.Category.UrlSlug)</p>
                    <p class="post-meta"> 
                        Tags:
                        @foreach(var ptm in post.PostTagMaps)
                        {
                            <span class="post-tag">
                                @Html.TagLink(ptm.Tag.Name, ptm.Tag.UrlSlug)
                            </span>
                        }
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
        </div>
        <!-- post lists -->
        <div class="row col-3">
            @await Component.InvokeAsync("MostViewed")
            @await Component.InvokeAsync("LatestPosts")
        </div>
    </div>
    <!-- about card-->
    @Html.Partial("/Views/Home/_PartialAboutCard.cshtml")
</div>

FA.JustBlog/Views/Post/_ListPosts.cshtml
@{
    var mostViewed = TempData["mostViewedPosts"] as IList<FA.JustBlog.Core.Models.Post>;
    var lastestPost = TempData["lastestPosts"] as IList<FA.JustBlog.Core.Models.Post>;
}
<div class="row col-3">
    <div class="col-12">
        <h3>Most viewed posts</h3>
        @foreach (var p in mostViewed)
        {
            <div class="single-most-viewed">
                <span>
                    <a asp-controller="Post" asp-action="PostDetails" asp-route-id="@p.Id">@p.Title</a>
                </span>
            </div>
        }
    </div>
    <div class="col-12">
        <h3>Lastest posts</h3>
        @foreach (var p in lastestPost)
        {
            <div class="single-lastest">
                <span>
                    <a asp-controller="Post" asp-action="PostDetails" asp-route-id="@p.Id">@p.Title</a>
                </span>
            </div>
        }
    </div>
</div>