FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostRepo postRepo;
        public PostController(IPostRepo repo)
        {
            postRepo = repo;
        }

        //display all posts
        public IActionResult Index()
        {
            IList<Post> posts = postRepo.GetAllPosts();
            return View(posts);
        }

        //display single post by id
        public IActionResult PostDetails(int id)
        {
            Post post = postRepo.FindPostById(id);
            if (post == null)
            {
                return NoContent();
            }
            return View("Views/Post/Details.cshtml", post);
        }

        //display latest posts
        public IActionResult LastestPosts(int size = 5)
        {
            IList<Post> posts = postRepo.GetLatestPost(size);
            return View("Views/Post/Index.cshtml", posts);
        }

        //[System.Web.Mvc.ChildActionOnly]
        public IActionResult AboutCard()
        {
            return PartialView("_PartialAboutCard");
        }

        public Post GetPostById(int id)
        {
            return postRepo.FindPostById(id);
        }

        [Route("post/{year}/{month}/{urlslug}")]
        public ActionResult Details(int year, int month, string urlslug)
        {
            var post = postRepo.FindPost(year, month, urlslug);
            if (post == null)
                return NotFound();
            return View(post);
        }

        // get post by category name
        [Route("post/category/{category}")]
        public IActionResult Category(string category)
        {
            try
            {
                IList<Post> postsByCate = postRepo.GetPostsByCategory(category);
                return View("Views/Post/Index.cshtml", postsByCate);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(ReturnErrorView));
            }
        }

        // get posts by tag name
        [Route("post/tag/{tagUrlSlug}")]
        public IActionResult Tag(string tagUrlSlug)
        {
            try
            {
                IList<Post> postsByTag = postRepo.GetPostsByTag(tagUrlSlug);
                return View("Views/Post/Index.cshtml", postsByTag);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(ReturnErrorView));
            }
        }

        [HttpPost]
        //[Route("post/search")]
        public IActionResult Search(string query)
        {
            IList<Post> posts = postRepo.FindPostByTitleOrDescription(query);
            return View("Views/Post/Index.cshtml", posts);
        }
        public ViewResult ReturnErrorView()
        {
            return View("Views/Shared/Error.cshtml");
        }
    }
}

FA.JustBlog/ViewComponents/MenuViewComponent.cs
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;
namespace FA.JustBlog.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly ICategoryRepo _categoryRepository;

        public MenuViewComponent(ICategoryRepo categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public IViewComponentResult Invoke()
        {
            var categories = _categoryRepository.GetAllCategories();
            return View(categories);
        }

    }
}

FA.JustBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-controller="Post" asp-action="Index">Just blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Post" asp-action="Index">Home</a>
                        </li>
                    @await Component.InvokeAsync("Menu")
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Contact</a></li>
                    @* search blogs *@
                    <partial name="_SearchBar"/>
                </ul>
                <partial name="_LoginPartial"/>
                <div id="google_translate_element"></div>
            </div>
        </div>
    </nav>

    @RenderBody()

    <!-- Footer-->
    @Html.Partial("_PartialFooter")
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement(
                { pageLanguage: 'en' },
                'google_translate_element'
            );
        }
    </script>
    <script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FA.JustBlog/Views/Shared/_PartialFooter.cshtml
<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
            </div>
        </div>
    </div>
</footer>

FA.JustBlog/Views/Shared/_SearchBar.cshtml
<li class="nav-item">
    <form asp-action="Search" method="post">
        <div class="form-group">
            <input class="nav-link px-lg-2  py-lg-3" name="query" placeholder="Search blogs..." style="width=50%"/>
        </div>
    </form>
</li>

FA.JustBlog/Views/Shared/_SelectLanguagePartial.cshtml
﻿@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture"
                                                                                                               onchange="this.form.submit();"
                                                                                                               asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>